regions = {};

regions{1}  = ...
    { 'Hubei_China'        ,...
      'Anhui_China'        ,...
      'Beijing_China'      ,...
      'Chongqing_China'    ,...
      'Fujian_China'       ,...
      'Gansu_China'        ,...
      'Guangdong_China'    ,...
      'Guangxi_China'      ,...
      'Guizhou_China'      ,...
      'Hainan_China'       ,...
      'Hebei_China'        ,...
      'Heilongjiang_China' ,...
      'Henan_China'        ,...
      'HongKong_China'     ,...
      'Hunan_China'        ,...
      'InnerMongolia_China',...
      'Jiangsu_China'      ,...
      'Jiangxi_China'      ,...
      'Jilin_China'        ,...
      'Liaoning_China'     ,...
      'Macau_China'        ,...
      'Ningxia_China'      ,...
      'Qinghai_China'      ,...
      'Shaanxi_China'      ,...
      'Shandong_China'     ,...
      'Shanghai_China'     ,...
      'Shanxi_China'       ,...
      'Sichuan_China'      ,...
      'Tianjin_China'      ,...
      'Tibet_China'        ,...
      'Xinjiang_China'     ,...
      'Yunnan_China'       ,...
      'Zhejiang_China' };    

regions{2} = {'Japan', 'Thailand', 'Vietnam', 'Philippines', 'Cambodia'};

regions{3}  = {'Tasmania_Australia'                 ,...
                  'Victoria_Australia'                  ,...
                  'AustralianCapitalTerritory_Australia',...
                  'SouthAustralia_Australia'            ,...
                  'NewSouthWales_Australia'             ,...
                  'WesternAustralia_Australia'          ,...
                  'Queensland_Australia'                ,...
                  'NorthernTerritory_Australia' ,'NewZealand' };

regions{4} = {'Malaysia', 'Singapore', 'SriLanka'};


regions{5} = {'Italy', 'Spain', 'UK', 'US', 'Germany', 'Israel', 'France', 'Denmark', 'Sweden','Norway','Poland','Finland', 'Canada'};

regions{6} = { 'SouthAfrica','Venezuela','Brazil','Argentina','Paraguay'};

regions;