global regions;
global regionsA;
global regionsB;
global regionsC;

regionsA = {};

regionsA{1}  = ...
    { 'Hubei_China'        ,...
      'Anhui_China'        ,...
      'Beijing_China'      ,...
      'Chongqing_China'    ,...
      'Fujian_China'       ,...
      'Gansu_China'        ,...
      'Guangdong_China'    ,...
      'Guangxi_China'      ,...
      'Guizhou_China'      ,...
      'Hainan_China'       ,...
      'Hebei_China'        ,...
      'Heilongjiang_China' ,...
      'Henan_China'        ,...
      'HongKong_China'     ,...
      'Hunan_China'        ,...
      'InnerMongolia_China',...
      'Jiangsu_China'      ,...
      'Jiangxi_China'      ,...
      'Jilin_China'        ,...
      'Liaoning_China'     ,...
      'Macau_China'        ,...
      'Ningxia_China'      ,...
      'Qinghai_China'      ,...
      'Shaanxi_China'      ,...
      'Shandong_China'     ,...
      'Shanghai_China'     ,...
      'Shanxi_China'       ,...
      'Sichuan_China'      ,...
      'Tianjin_China'      ,...
      'Tibet_China'        ,...
      'Xinjiang_China'     ,...
      'Yunnan_China'       ,...
      'Zhejiang_China' };    

regionsA{2} = {'Japan', 'Thailand', 'Vietnam', 'Philippines', 'Cambodia'};

regionsA{3}  = {'Tasmania_Australia'                 ,...
                  'Victoria_Australia'                  ,...
                  'AustralianCapitalTerritory_Australia',...
                  'SouthAustralia_Australia'            ,...
                  'NewSouthWales_Australia'             ,...
                  'WesternAustralia_Australia'          ,...
                  'Queensland_Australia'                ,...
                  'NorthernTerritory_Australia' ,'NewZealand' };

regionsA{4} = {'Malaysia', 'Singapore', 'SriLanka'};


regionsA{5} = {'Italy', 'Spain', 'UK', 'US', 'Germany', 'Israel', 'France', 'Denmark', 'Sweden','Norway','Poland','Finland', 'Canada'};

regionsA{6} = { 'SouthAfrica','Venezuela','Brazil','Argentina','Paraguay'};

regions;

regionsB = {};
regionsC = {};

regionsB{1}  = ...
    { 'Hubei_China', 'Japan', 'Thailand', 'NewSouthWales_Australia', 'Vietnam', 'Philippines', 'Cambodia'};

regionsB{2}  = {'Taiwan_', 'Korea_South', 'Malaysia', 'SriLanka','Singapore'}; 

regionsB{3}  = {'US', 'Finland', 'Canada', 'UK', 'France', 'Nepal'};

regionsB{4}  = {'UnitedArabEmirates', 'Cambodia', 'Germany', 'Victoria_Australia', 'Spain'};


regionsB{5} = {'India', 'Belgium', 'SouthAustralia_Australia', 'Iran', 'Italy', 'Queensland_Australia' };


regionsB{6} = {'Israel', 'Egypt', 'Oman', 'WesternAustralia_Australia', 'Switzerland', 'Mexico'};


regionsC{1}  = {'Finland', 'Canada', 'UK', 'Germany', 'Belgium', 'Switzerland'};
regionsC{2} = {'France', 'Italy', 'Spain', 'US', 'Japan'};
regionsC{3} = {'Korea_South', 'Iran', 'Hubei_China', 'Israel', 'Nepal', 'Egypt'};
regionsC{4} = {'UnitedArabEmirates', 'Taiwan_', 'Mexico', 'India', 'Oman'};
regionsC{5} = {'Vietnam', 'Thailand', 'Philippines', 'Cambodia', 'SriLanka', 'Malaysia'};
regionsC{6} = {'Singapore', 'Queensland_Australia' , 'WesternAustralia_Australia', 'NewSouthWales_Australia', 'SouthAustralia_Australia', 'Victoria_Australia'};

regions = regionsA;